### PR TITLE
Display original error on failure

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Review by cpu — APPROVED** [review]
@djc This looks like an uncontroversial fix that might be nice to clear out of the PR queue. 

There was a Macos CI failure but the job logs have already been purged and I don't have permissions to re-run. Could you kick the build and see if it was something transient?

**Comment by djc** [comment]
It's interesting that the `apple` test fails on beta/ubuntu-20.04 1.59.0/ubuntu-20.04 but passes on stable/ubuntu-20.04, nightly/ubuntu-20.04, stable/macos and stable/windows. Seems like an intermittent issue, maybe they're doing some kind of rate limiting?

I tried running it a bunch of times in rapid succession locally, but it passed every time.

**Comment by cpu** [comment]
> Seems like an intermittent issue, maybe they're doing some kind of rate limiting?

I was curious (and already looking at some CI failures today) so I tried hammering apple.com a bit from a test GHA repo. I _was_ able to reproduce the issue with `openssl s_client` in a tight loop, but not reliably. In approx. 1 in 10 runs, I'd get a failure after ~25 connections. I saw similar tweaking the `rustls-native-certs` GHA to run just the apple.com smoke test in a loop of 50 runs. Most completely successfully, one failed on the 26th connection. I concur that it seems like rate limiting or a WAF :shrug: Frustrating!

**Comment by djc** [comment]
@ctz do you remember if there's a specific reason to include apple.com here? Do we suspect that they run a SecureTransport-based server which we'd like to try, or something?

**Comment by djc** [comment]
(Meanwhile, we probably shouldn't block this PR on the intermittent CI issues.)

**Comment by ctz** [comment]
> @ctz do you remember if there's a specific reason to include apple.com here? Do we suspect that they run a SecureTransport-based server which we'd like to try, or something?

It's really just a random selection of big company websites that came to mind at the time.

**Comment by djc** [comment]
Okay, maybe we should just get rid of the `apple` test? Seems like it's more trouble than it's worth at this point.

**Pull request merged**
