### PR TITLE
Android Platform Support

### PR DESCRIPTION
**Pull request by jruesga**
The implementation relies on Jni to access the Android KeyStore and obtain a list of trusted certificates. The code:

- Obtains and attach a previous created JVM instance.
- Uses JNI calls to access java.lang.Keystore and get the list of trusted certificates

```java
KeyStore ks = KeyStore.getInstance("AndroidCAStore");
ks.load(null);
Enumeration<String> enumeration = ks.aliases();
while (enumeration.hasMoreElements()) {
    Certificate certificate = enumeration.nextElement();
    byte[] der = certificate.getEncoded();
}
```
- Maps any der certificate and errors to a CertificateResult.

Related to https://github.com/rustls/rustls-native-certs/issues/3

There are GitHub Actions Android worflows included (both passing https://github.com/jruesga/rustls-native-certs/actions):

- rustls: it compiles the code for each Android ABI
- smoke-test: runs Android instrumentation tests for `compare_mozilla.rs` and `smoketests.rs`.

### CODE REVIEW

**Comment by djc** [comment]
Is there a reason you can't use the rustls-platform-verifier crate? It is currently the preferred way, see the current README.

**Comment by jruesga** [comment]
No. I read the README and understood that rustls-platform-verifier is the preferred way on wards. Just wanted to contribute it.

**Comment by djc** [comment]
So why do you want to contribute it? Does rustls-platform-verifier not work for your use case?

**Comment by jruesga** [comment]
yes, it does. Just learning new stuff. You can close the pull request. I understand that rustls-platform-verifier is the path forward.

**Pull request closed without merging**
