### PR TITLE
Allows loading certificates from a specific directory or file.

### PR DESCRIPTION
**Pull request by mokeyish**

### CODE REVIEW

**Comment by djc** [comment]
Why do you want this?

**Comment by mokeyish** [comment]
> Why do you want this?

Hi, I want to implement the following features in Rust.

图片

**Comment by cpu** [comment]
IMO this feature doesn't seem to blend well with the goals of this particular crate, certs from a directory on disk aren't really native certs to a specific platform.

Perhaps it would be better to write a companion to the `certs` function of the [`rustls-pemfile`](https://github.com/rustls/pemfile) crate that could adapt a directory to `io::BufRead` instances to be parsed?

**Comment by mokeyish** [comment]
Ok, I close this PR.

**Pull request closed without merging**
